# Generated by Django 3.0.6 on 2020-05-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_item_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oredered_date',
            new_name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
