# Generated by Django 3.0.6 on 2020-05-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200528_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('N', 'new'), ('P', 'popular'), ('S', 'sale')], max_length=1),
        ),
    ]
