# Generated by Django 3.0.6 on 2020-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200530_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.CharField(default='abc123@gmail.com', max_length=64),
            preserve_default=False,
        ),
    ]
