# Generated by Django 3.0.6 on 2020-06-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_billingaddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='rob'),
            preserve_default=False,
        ),
    ]
