# Generated by Django 3.0.6 on 2020-06-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_order_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('MW', 'Mens Wear'), ('WW', 'Womens Wear'), ('EC', 'Electronics'), ('FW', 'Foot Wear')], max_length=2)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
