# Generated by Django 3.0.6 on 2020-06-02 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.DiscountCode'),
        ),
    ]
