# Generated by Django 3.0.6 on 2020-06-02 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_order_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DiscountCode'),
        ),
    ]
