# Generated by Django 3.0.6 on 2020-06-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200602_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_code',
            new_name='dis_code',
        ),
    ]
